#!/usr/bin/env bash
# 101-tell_the_story_of_passwd: display content of /etc/passwd
# using a format:
#+ The user USERNAME is part of the GROUP_ID gang, 
#+ lives in HOME_DIRECTORY and rides COMMAND/SHELL. 
#+ USER ID's place is protected by the passcode PASSWORD, 
#+ more info about the user here: USER ID INFO

directory="/etc/passwd"
while IFS=":" read -r USERNAME PASSWORD USER_ID GROUP_ID USER_ID_INFO HOME_DIRECTORY COMMAND_SHELL;
do
	echo "The user $USERNAME is part of the $GROUP_ID gang, lives in $HOME_DIRECTORY and rides $COMMAND_SHELL. $USER_ID's place is protected by the passcode $PASSWORD, more info about the user here: $USER_ID_INFO"
done < $directory
