#!/usr/bin/env bash
# 4-if_9_say_hi: Displays Best School 10 time but hi for the 9th

count=1
while [ $count -ne 11 ]
do
	if [ $count -eq 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi

	((count++))
done
