#!/usr/bin/env bash
# 5-4_bad_luck_8_is_your_chance: displays Best school
#+ for every number between 10 except 4 and 8

count=0
while [ $count -ne 10 ]
do
	((count++))
	if [ $count -eq 4 ]
	then
		echo "bad luck"
	elif [ $count -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
done
