#!/usr/bin/env bash
# 9-to_file_or_not_to_file: script that gives you 
#+ information about the school file

# check if file exists: school file exists
#+ and check if it's empty: school file is empty
#+	else: school file is not empty
#+ and check if it's a regular file: school is a regular file
#+ elif file doesn't exist: school file does not exist

school_file="school"

# check if file exists
if [ -e "$school_file" ]
then
	echo "school file exists"
	# check if it's empty
	if [ ! -s "$school_file" ]
	then
		echo "school file is empty"
	else
		echo "school file is not empty"
	fi
	# check if it's a regular file
	if [ -f "$school_file" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
